# Site settings
title: Hamish Williams / Full-Process Designer
email: your-email@domain.com
description: "Yeah, I'm a designer"
baseurl: ""
url: "https://www.hamishw.com"
twitter_username: HamishMW
github_username:  HamishMW

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
sass:
    sass_dir: src/sass

# Ignore when compiling
exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - src