# Site settings
title: Hamish Williams – Full-Process Designer
email: your-email@domain.com
description: "Yeah, I'm a designer"
baseurl: ""
url: "http://hamishmw.github.io/"
twitter_username: HamishMW
github_username:  HamishMW

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap

# Ignore when compiling
exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - src